# Dependencies
markdown:         kramdown

# Permalinks
permalink:        pretty

# Setup
title:            Andrew's Blog
#tagline:          opinions and news
url:              https://andrew222651.com
paginate:         6
author:
  name:           Andrew MacFie

excerpt_separator: "\n\n"

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/andrew222651/andrew222651.github.io

pages_list:
    'All posts': '/archive'
    Feed: '/atom.xml'
    About: '/about'

plugins: [jekyll-paginate]

theme:
