# Dependencies
markdown:         kramdown

# Permalinks
permalink:        pretty

# Setup
title:            Andrew's Blog
#tagline:          opinions and news
url:              http://amacfie.github.io
paginate:         6
author:
  name:           Andrew MacFie

excerpt_separator: "\n\n"

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/amacfie/amacfie.github.io

pages_list:
    'All posts': '/archive'
    Feed: '/atom.xml'
    About me: '/about'

plugins: [jekyll-paginate]

