# Dependencies
markdown:         kramdown
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Andrew MacFie's Blog
tagline:          opinions and news
url:              http://amacfie.github.io
paginate:         3
author:
  name:           Andrew MacFie

excerpt_separator: "\r\n\r\n"

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/amacfie/amacfie.github.io

pages_list:       
    Archive: '/archive'
    Feed: '/atom.xml'
