# Dependencies
markdown:         kramdown
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Andrew MacFie's Blog
tagline:          tagline
url:              http://amacfie.github.io
paginate:         1
author:
  name:           Andrew MacFie

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/amacfie/amacfie.github.io

pages_list:       
    About: '/about'
    Archive: '/archive'
    Feed: '/atom.xml'
